name: Build and Scan Image
on:
  workflow_call:
    inputs:
      AWS_REGION:
        required: true
        type: string
      AWS_ACCOUNT_ID:
        required: true
        type: string
      IMAGE_NAME:
        required: true
        type: string  
    secrets:
      REGISTRY:
        required: true
      GITHUB_TOKEN:
        required: true
jobs:
  build-image:
    name: Build, Scan Image and Push on PR merge
    runs-on: [self-hosted, linux, build]
    defaults:
      run:
        shell: bash
    steps:
    - name: Get Code
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ input.AWS_REGION }}
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/ecr-image-push
        role-duration-seconds: 3600
        role-session-name: GithubActions-PushImage

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: ${{ input.PULL_REQUEST }}
        context: .
        tags: |
          ${{ secrets.REGISTRY }}/${{ input.IMAGE_NAME }}:${{ github.sha }}
          ${{ secrets.REGISTRY }}/${{ input.IMAGE_NAME }}:latest
