name: Helm Linter
on:
  pull_request:
    types:
      - opened
      - synchronize
  pull_request_target:
    types:     
      - closed
jobs:
  helmchart-linter:
    name: Helm Chart Linter
    runs-on: ubuntu-latest
    container: quay.io/helmpack/chart-testing
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run chart-testing (list-changed)
      id: list-changed
      run: |
        changed=$(ct list-changed --target-branch ${{ github.base_ref }})
        if [[ -n "$changed" ]]; then
          echo "::set-output name=changed::true"
        fi

    - name: Run chart-testing (lint)
      run: ct lint --chart-dirs infra/agoro-adviser-backend

    - name: Create kind cluster
      uses: helm/kind-action@v1.2.0
      if: steps.list-changed.outputs.changed == 'true'

    - name: Run chart-testing (install)
      run: ct install --target-branch ${{ github.base_ref }}
