name: Nodejs code check
on:
  pull_request:
    types:
      - opened
      - synchronize
      - closed
  workflow_call:
    secrets:    
      GITHUB_TOKEN:
        required: true

jobs:      
  pr-title:
    name: Semantic Pull Request Title
    runs-on: ubuntu-latest
    steps:
      - name: Semantic Pull Request Title
        uses: amannn/action-semantic-pull-request@v3.4.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          validateSingleCommit: true
