name: Release
on:
  push:
    tags:
      - '**'
    branches-ignore:
      - '**'

env:
  IMAGE_NAME: <image name for ecr>

jobs:
  get_env:
    name: Set Env
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    outputs:
      ENV_NAME: ${{ steps.get_env.outputs.ENV_NAME }}
      TAG: ${{ steps.get_env.outputs.TAG }}
    steps:
      - name: Set env variable
        run: |
            mapfile -d \- -t temp < <(echo ${{ github.ref_name }})
            echo "::set-output name=ENV_NAME::${temp[0]}"
            echo "::set-output name=TAG::${temp[1]}"
        id: get_env

  retag_image:
    name: Tag docker sha with ${{ github.ref_name }}
    runs-on: ubuntu-latest
    default:
      run:
        shell: bash
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/ecr-image-push
          role-duration-seconds: 3600
          role-session-name: GithubActions-PushImage
      
      - name: Retag
        run: |
          docker pull ${{ secrets.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          docker tag ${{ secrets.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} ${{ secrets.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
          docker push ${{ secrets.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}

  deploy:
    name: Deploy App
    needs:
      - get_env
      - retag_image
    uses: agorocarbon/reusable-workflows/.github/workflows/deploy.yaml@main
    with:
      IMAGE_NAME: ${{ env.IMAGE_NAME }}
      IMAGE_TAG: ${{ github.ref_name }}
      USERNAME: ${{ github.actor }}
    secrets:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      REGISTRY: ${{ secrets.REGISTRY }}
      CLUSTER_NAME: ${{ secrets. EKS_CLUSTER_NAME }}
