name: Nodejs code check
on:
  push:
    branches-ignore:
      - main
      - master
  pull_request:
    types:
      - opened
      - synchronize
  pull_request_target:
    types:    
      - closed

env:
  IMAGE_NAME:

jobs:
  setup_env:
    name: Setup Env
    runs-on: ubuntu-latest
    container:
      image: node:14
    defaults:
      run:
        shell: bash
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
    - name: Get Code
      uses: actions/checkout@v2

    - name: Get yarn cache directory path
      run: echo "YARN_CACHE_DIR=$(yarn cache dir)" >> $GITHUB_ENV

    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: ${{ env.YARN_CACHE_DIR }}
        key: ${{ github.repository }}-${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ github.repository }}-${{ runner.os }}-yarn-

    - name: Install node dependencies to populate cache
      run: yarn install --frozen-lockfile

  code_linter:
    name: Code Linter
    needs: 
      - setup_env
    runs-on: ubuntu-latest
    container: node:14
    defaults:
      run:
        shell: bash
    steps:
    - name: Get Code
      uses: actions/checkout@v2

    - name: Get yarn cache directory path
      run: echo "YARN_CACHE_DIR=$(yarn cache dir)" >> $GITHUB_ENV

    - name: Cache node modules
      id: yarn-cache
      uses: actions/cache@v2
      with:
        path: ${{ env.YARN_CACHE_DIR }}
        key: ${{ github.repository }}-${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ github.repository }}-${{ runner.os }}-yarn-

    - name: Install node dependencies
      run: yarn install --frozen-lockfile

    - name: Code Quality Run Lint
      run: yarn lint

  unit_tests:
    name: Unit Tests
    environment: Testing
    needs:
      - setup_env
    uses: agorocarbon/reusable-workflows/.github/workflows/tests_nodejs.yaml@main
    with:
      TEST_TYPE: cov

  e2e_tests:
    name: E2E Tests
    environment: Testing
    needs:
      - setup_env
    uses: agorocarbon/reusable-workflows/.github/workflows/tests_nodejs.yaml@main
    with:
      TEST_TYPE: e2e
  
  build_image:
    name: Build Image
    needs:
      - unit_tests
      - e2e_tests
    uses: agorocarbon/reusable-workflows/.github/workflows/build_image.yaml@main
    with:
      IMAGE_NAME: ${{ env.IMAGE_NAME }}
      IMAGE_TAG: ${{ github.sha }}
    secrets:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      REGISTRY: ${{ secrets.REGISTRY }}

  deploy:
    name: Deploy App
    environment: Staging
    needs:
      - build_image
    uses: agorocarbon/reusable-workflows/.github/workflows/deploy.yaml@main
    with:
      IMAGE_NAME: ${{ env.IMAGE_NAME }}
      IMAGE_TAG: ${{ github.sha }}
      USERNAME: ${{ github.actor }}
    secrets:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      REGISTRY: ${{ secrets.REGISTRY }}
      CLUSTER_NAME: ${{ secrets. EKS_CLUSTER_NAME }}
